package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// getGolangDirs - Получение слайса директорий, содержащих .go файлы
// (файлы с суффиксом .gen.go или _test.go упускаются)
func getGolangDirs(dir string) ([]string, error) {
	// Для составления списка файлов воспользуемся мапой, так мы избавимся от потенциальных дубликатов файлов
	files := make(map[string]bool)

	err := filepath.Walk(dir, func(path string, info os.FileInfo, skip error) error {
		// Если в skip != nil - значит на шаге выше было принято решение пропустить проверку всей ветки этого пути
		// Чтобы исполнить это решение - нужно вернуть ошибку и закончить обработку
		if skip != nil {
			return skip
		}

		// Обработка директории
		if info.IsDir() {
			if name := info.Name(); strings.HasPrefix(name, ".") && name != "." {
				return filepath.SkipDir
			}

			return nil
		}

		// Обработка файла с суффиксом .go
		if strings.HasSuffix(info.Name(), ".go") {
			if strings.HasSuffix(info.Name(), ".gen.go") || strings.HasSuffix(info.Name(), "_test.go") {
				return nil
			}

			files[filepath.Dir(path)] = true
		}

		return nil
	})
	if err != nil {
		return nil, err
	}

	// В результат передаём слайс ключей от мапы
	return slices.Collect(maps.Keys(files)), nil
}

// getStructInfo - Получение информации по структурам требующим генерации метода Reset() среди переданных директорий
func getStructInfo(fset *token.FileSet, dirs []string) (map[string]bool, map[string][]StructInfo, error) {
	// structNames - Список всех названий структур обладающих сгенерированным методом Reset()
	structNames := make(map[string]bool)

	// structByPkg - Мапа в формате ["пакет" => ...слайс структур которым нужен метод Reset()]
	structByPkg := make(map[string][]StructInfo)

	for _, dir := range dirs {
		entries, err := os.ReadDir(dir)
		if err != nil {
			return structNames, structByPkg, fmt.Errorf("ошибка при чтении директории %s: %w", dir, err)
		}

		for _, entry := range entries {
			if entry.IsDir() {
				continue
			}
			name := entry.Name()
			if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == "reset.gen.go" {
				continue
			}

			filePath := filepath.Join(dir, name)
			file, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
			if err != nil {
				return structNames, structByPkg, fmt.Errorf("ошибка при парсинге файла %s: %w", filePath, err)
			}

			pkgName := file.Name.Name

			// Проходим по всем объявлениям
			for _, decl := range file.Decls {

				// Пропускаем все объявления, кроме объявлений кастомных типов
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}

				// Т.к. в type (...) можно объявить несколько структур - проходим по каждому объекту объявления отдельно
				for _, spec := range genDecl.Specs {
					// Оставляем только объявления структур
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					// Проверяем наличие комментария // generate:reset рядом с объявлением или элементом объявления
					hasReset := hasGenerateReset(genDecl.Doc) || hasGenerateReset(typeSpec.Doc)
					if hasReset {
						structName := typeSpec.Name.Name
						structNames[structName] = true
						structByPkg[dir] = append(structByPkg[dir], StructInfo{
							PkgPath:    dir,
							PkgName:    pkgName,
							StructName: structName,
							StructType: structType,
						})
					}
				}
			}
		}
	}

	return structNames, structByPkg, nil
}

// generateResetFiles - Создание reset.gen.go
func generateResetFiles(fset *token.FileSet, structNames map[string]bool, structByPkg map[string][]StructInfo) error {

	// Генерируем reset.gen.go файлы
	for path, structs := range structByPkg {
		// Если вдруг попал пустой слайс - пропускаем обработку
		if len(structs) == 0 {
			continue
		}

		pkgName := structs[0].PkgName

		var buf bytes.Buffer
		buf.WriteString("// Code generated by reset generator. DO NOT EDIT.\n\n")
		buf.WriteString(fmt.Sprintf("package %s\n\n", pkgName))

		for _, s := range structs {
			structField := "rs"
			buf.WriteString(fmt.Sprintf("func (%s *%s) Reset() {\n", structField, s.StructName))
			buf.WriteString("    if " + structField + " == nil {\n")
			buf.WriteString("        return\n")
			buf.WriteString("    }\n\n")

			for _, field := range s.StructType.Fields.List {
				if len(field.Names) == 0 {
					continue
				}
				for _, name := range field.Names {
					fieldName := name.Name
					stmt := generateFieldReset(structField, fieldName, field.Type, fset, structNames)
					buf.WriteString("    " + stmt + "\n")
				}
			}
			buf.WriteString("}\n\n")
		}

		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error formatting code for %s: %v\nCode:\n%s\n", path, err, buf.String())
			continue
		}

		genFilePath := filepath.Join(path, "reset.gen.go")
		err = os.WriteFile(genFilePath, formatted, 0644)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", genFilePath, err)
		} else {
			fmt.Printf("Generated %s\n", genFilePath)
		}
	}

	return nil
}

// hasGenerateReset - Проверка наличия комментария generate:reset у блока комментариев
func hasGenerateReset(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	success := false

	for _, comment := range doc.List {
		if strings.HasPrefix(strings.TrimSpace(comment.Text), "// generate:reset") {
			success = true
		}
	}

	return success
}

// generateFieldReset - Сброс значения поля
func generateFieldReset(structField, fieldName string, expr ast.Expr, fset *token.FileSet, resetStructs map[string]bool) string {
	toStr := func(e ast.Expr) string {
		var buf bytes.Buffer
		printer.Fprint(&buf, fset, e)
		return buf.String()
	}

	getZeroValue := func(name string) (string, bool) {
		switch name {
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
			"float32", "float64", "complex64", "complex128":
			return "0", true
		case "bool":
			return "false", true
		case "string":
			return `""`, true
		}
		return "", false
	}

	getName := func(e ast.Expr) string {
		switch x := e.(type) {
		case *ast.Ident:
			return x.Name
		case *ast.SelectorExpr:
			return x.Sel.Name
		}
		return ""
	}

	path := fmt.Sprintf("%s.%s", structField, fieldName)

	switch t := expr.(type) {
	case *ast.MapType:
		return fmt.Sprintf("clear(%s)", path)
	case *ast.ArrayType:
		if t.Len == nil {
			return fmt.Sprintf("if %s != nil { %s = %s[:0] }", path, path, path)
		}
	case *ast.StarExpr:
		elem := t.X
		name := getName(elem)
		if zero, ok := getZeroValue(name); ok {
			return fmt.Sprintf("if %s != nil { *%s = %s }", path, path, zero)
		}
		if resetStructs[name] {
			return fmt.Sprintf("if %s != nil { %s.Reset() }", path, path)
		}
		return fmt.Sprintf("if %s != nil { *%s = %s{} }", path, path, toStr(elem))
	case *ast.Ident, *ast.SelectorExpr:
		name := getName(expr)
		if zero, ok := getZeroValue(name); ok {
			return fmt.Sprintf("%s = %s", path, zero)
		}
		if resetStructs[name] {
			return fmt.Sprintf("%s.Reset()", path)
		}
	}

	return fmt.Sprintf("%s = %s{}", path, toStr(expr))
}
